$extends$: configs/base_config.yaml

evaluators:
  - name: classification
    args:
      dataset: nli
      dataset_name: multi_nli

dataset: our_nli
dataset_name: multi_nli

hardness_key: hardness:gaussian_mixture

hardness:
  - easy
  - ambigous
  - hard